### ISSUE TITLE
Dockerise the project

### ISSUE THREAD

**Issue by unownone** [unownone/Tweety.py#5]
# Summary
The project has multiple dependencies like a `python server` as well as a `mongodb` instance. Overtime that requirement can increase.
Dockerising the project can ensure easier first time setup for developers working on it!

# Suggestions:
Use docker compose to spin up multiple containers , one for `mongodb` one for the fastapi server making it more easy to use and efficient. Some ENV changes may be required . [This Article](https://docs.docker.com/compose/gettingstarted/) can be a good place to start from.

**Comment by hmajid2301** [comment]
I can do this; is there a list of all the deps you use ? i.e. MongoDB that need to be dockerised

**Comment by unownone** [comment]
@hmajid2301 Hey! Thanks for the reply.  It only requires MongoDB , and you can choose a Fastapi or official python images for the server base! 
Cheerio! 

PS: Make sure to make the PR on or after 1st october though.
